# Generated by Django 6.0.2 on 2026-02-16 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('monday_user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_users',
                'constraints': [models.UniqueConstraint(fields=('app_name', 'monday_user_id'), name='app_users_app_name_monday_user_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('account_id', models.CharField(db_index=True, max_length=255)),
                ('board_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused_rate_limited', 'Paused (rate limited)')], db_index=True, default='pending', max_length=32)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Immediate'), ('run_at', 'Run at'), ('cron', 'Cron'), ('delay_from_now', 'Delay from now'), ('polling', 'Polling')], max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('polling_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('polling_state', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='common.appuser')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('attempt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('error_type', models.CharField(blank=True, choices=[('transient', 'Transient'), ('permanent', 'Permanent')], max_length=32, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='common.job')),
            ],
            options={
                'db_table': 'job_logs',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['app_name', 'status'], name='jobs_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scheduled_at', 'status'], name='jobs_scheduled_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['account_id'], name='jobs_account_id_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['job', 'created_at'], name='job_logs_job_created_idx'),
        ),
    ]
